// Generated by Framer (0ea0c8c)

import { addFonts, addPropertyControls, ControlType, cx, getFonts, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Crescent from "../vector/ytGW9Q6Qd";
import Sun from "../vector/ZuJJ7IgwO";
const SunFonts = getFonts(Sun);
const CrescentFonts = getFonts(Crescent);

const enabledGestures = {fFQmV9nZU: {pressed: true}, sE9LAw_1G: {pressed: true}};

const cycleOrder = ["fFQmV9nZU", "sE9LAw_1G"];

const serializationHash = "framer-4gMAy"

const variantClassNames = {fFQmV9nZU: "framer-v-y7rje7", sE9LAw_1G: "framer-v-buhh5r"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const v4eV4BTu7 = undefined

const transition1 = {bounce: 0.3, delay: 0, duration: 0.5, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const humanReadableVariantMap = {Dark: "sE9LAw_1G", Light: "fFQmV9nZU"}

const Variants = motion.create(React.Fragment)

const getProps = ({height, id, width, ...props}) => { return {...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "fFQmV9nZU"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "fFQmV9nZU", enabledGestures, ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.button {...restProps} {...gestureHandlers} aria-label={"theme switcher"} className={cx(scopingClassNames, "framer-y7rje7", className, classNames)} data-framer-name={"Light"} data-reset={"button"} layoutDependency={layoutDependency} layoutId={"fFQmV9nZU"} ref={refBinding} style={{...style}} {...addPropertyOverrides({"fFQmV9nZU-pressed": {"data-framer-cursor": v4eV4BTu7, "data-framer-name": undefined}, "sE9LAw_1G-pressed": {"data-framer-cursor": v4eV4BTu7, "data-framer-name": undefined}, sE9LAw_1G: {"data-framer-name": "Dark"}}, baseVariant, gestureVariant)}><Sun animated className={"framer-1nruxe2"} data-framer-name={"sun"} layoutDependency={layoutDependency} layoutId={"LDLBavwxk"} style={{"--18am8rn": "var(--token-5a490139-f600-4070-9d38-c970d0cb8aa1, rgb(26, 26, 26))", opacity: 0, rotate: 120, scale: 0.5}} variants={{sE9LAw_1G: {opacity: 1, rotate: 0, scale: 1}}} {...addPropertyOverrides({"fFQmV9nZU-pressed": {"data-framer-cursor": v4eV4BTu7}, "sE9LAw_1G-pressed": {"data-framer-cursor": v4eV4BTu7}}, baseVariant, gestureVariant)}/><Crescent animated className={"framer-12ucz9g"} layoutDependency={layoutDependency} layoutId={"IwE0mq2l7"} style={{"--18am8rn": "var(--token-5a490139-f600-4070-9d38-c970d0cb8aa1, rgb(26, 26, 26))", opacity: 1, rotate: 0, scale: 1}} variants={{"fFQmV9nZU-pressed": {opacity: 1, rotate: 0, scale: 1}, sE9LAw_1G: {opacity: 0, rotate: 120, scale: 0.5}}} {...addPropertyOverrides({"fFQmV9nZU-pressed": {"data-framer-cursor": v4eV4BTu7}, "sE9LAw_1G-pressed": {"data-framer-cursor": v4eV4BTu7}}, baseVariant, gestureVariant)}/></motion.button></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-4gMAy.framer-12vixej, .framer-4gMAy .framer-12vixej { display: block; }", ".framer-4gMAy.framer-y7rje7 { cursor: pointer; gap: 8px; height: 20px; overflow: visible; position: relative; width: 20px; }", ".framer-4gMAy .framer-1nruxe2, .framer-4gMAy .framer-12ucz9g { bottom: 0px; flex: none; height: var(--framer-aspect-ratio-supported, 20px); left: 0px; position: absolute; right: 0px; width: calc(100% - 0px); }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 20
 * @framerIntrinsicWidth 20
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"sE9LAw_1G":{"layout":["fixed","fixed"]},"GCcWTWmOd":{"layout":["fixed","fixed"]},"SfVXhn0y7":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerTNs__iJX1: React.ComponentType<Props> = withCSS(Component, css, "framer-4gMAy") as typeof Component;
export default FramerTNs__iJX1;

FramerTNs__iJX1.displayName = "theme-switcher";

FramerTNs__iJX1.defaultProps = {height: 20, width: 20};

addPropertyControls(FramerTNs__iJX1, {variant: {options: ["fFQmV9nZU", "sE9LAw_1G"], optionTitles: ["Light", "Dark"], title: "Variant", type: ControlType.Enum}} as any)

addFonts(FramerTNs__iJX1, [{explicitInter: true, fonts: []}, ...SunFonts, ...CrescentFonts], {supportsExplicitInterCodegen: true})